sudo: false
language: php

env:
    - APPENGINE_VERSION=1.9.25

php:
    - 5.4
    # Not ready to get php 5.5 testing ready ...
    # will require a change to the invocation of dev_appserver.py
    # so that it uses the php 5.5 binary.
    #- 5.5

before_script:
    - rm -rf google_appengine
    - mkdir -p logs
    - mkdir -p tests/coverage/
    - composer install --no-interaction --dev
    - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_$APPENGINE_VERSION.zip -nv
    - unzip -q google_appengine_$APPENGINE_VERSION.zip
    - patch -p0 < tests/patches/sdk-expose-remote-api-settings.patch
    - patch -p0 < tests/patches/sdk-appengine-logs.patch

script:
    - bash -c './google_appengine/dev_appserver.py tests/ --php_executable_path=$HOME/.phpenv/versions/$(phpenv version-name)/bin/php-cgi --skip_sdk_update_check --php_remote_debugging=yes & echo $! > appengine.pid'
    - vendor/bin/phpunit --coverage-clover logs/build.xml tests/

after_script:
    - bash -c 'cat appengine.pid | xargs kill'
    - cat logs/err.log
    - cat logs/appengine.log
    - php vendor/bin/coveralls -c coveralls.yml -v
